name: Snapshot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  snapshot:
    name: Snapshot
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Build package
        run: bun run build
      - name: Create snapshot
        id: snapshot
        run: bunx pkg-pr-new publish
